//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplicationMVCDotNetFramework.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChosenAnswer
    {
        public int Ansid { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Qid { get; set; }
        public Nullable<int> Userid { get; set; }
    
        public virtual Usertable Usertable { get; set; }
        public virtual OnlineExam OnlineExam { get; set; }
    }
}
